version: 2
jobs:
  build:
    working_directory: ~/Seg2105-lab3_test
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /opt/android/sdk
    steps:
      - checkout
      - run:
          name: Accept Android SDK licenses
          command: |
            mkdir -p $ANDROID_HOME/licenses
            echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > $ANDROID_HOME/licenses/android-sdk-license
            echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
          name: Install required Android SDK packages
          command: sdkmanager --install "build-tools;30.0.2" "platforms;android-29"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run UnitTest
          command: ./gradlew test
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
